name: Bump Version on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"

      - name: Update version in pyproject.toml
        run: |
          sed -i "s/^version = .*/version = \"${{ steps.get_version.outputs.VERSION }}\"/" pyproject.toml

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "chore: bump version to ${{ steps.get_version.outputs.VERSION }} [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
