name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch full git history
        run: git fetch --prune --unshallow || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build python-semantic-release

      - name: Run semantic release (version, changelog, tag, publish)
        run: python -m semantic_release publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Separate workflow (or job) for uploading release assets on tag push
# Save as .github/workflows/upload-release-assets.yml
