# .github/workflows/release-please.yml
name: Release & Artifacts with PAT

on:
  push:
    branches:
      - main

permissions:
  contents: write        # For tagging, changelog, and release creation
  pull-requests: write   # To open/update release PRs

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tool
        run: pip install --upgrade build

      - name: Build artifacts
        run: python -m build --outdir dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/*

  release:
    name: Generate Release PR & Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python

      - name: Download build artifacts
        if: needs.build.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: artifact/

      - name: Attach artifacts to GitHub Release
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ steps.release.outputs.tag_name }}" artifact/*

      - name: Trigger downstream workflows
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: echo "Release ${{ steps.release.outputs.tag_name }} created."
